### ISSUE TITLE
Specify the expected behavior of each test in ci-config.yml

### ISSUE THREAD

**Issue by mojtaba-eshghie** [mojtaba-eshghie/Clawk#53]
In the following 
```
tests:
  - name: "Exploit monitoring integration tests"
    directory: "/tests/exploits/"
    files:
      - "exp1.js"
    environment: "anvil" 
```

we can use enumerations for: 
_Exploit found or not found_
